# Change these first
owner: tdviet # Your GitHub username
repo: uptime-dynamic-dns-service # Your GitHub repository name

# Add your sites here
sites:
  - name: Dynamic DNS service
    url: https://nsupdate.fedcloud.eu

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.fedcloud.eu
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /uptime-dynamic-dns-service
  logoUrl: http://ups.savba.sk/pict/logo/logoangl767.gif
  name: IISAS web monitoring
  introTitle: "Monitoring web services at IISAS"
  introMessage: This is public monitoring of web services at IISAS 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
